# Generated by Django 4.0.4 on 2022-06-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('roll', models.IntegerField()),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('adhar', models.BigIntegerField()),
            ],
        ),
    ]
