# Generated by Django 4.0.4 on 2022-06-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='weight',
            field=models.FloatField(default=123, max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(default='XYZ', verbose_name='School Address'),
        ),
        migrations.AlterField(
            model_name='school',
            name='adhar',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='dob',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=15, null=True, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='roll',
            field=models.IntegerField(default=100, unique=True, verbose_name='Student Roll No'),
        ),
    ]
