# Generated by Django 4.0.4 on 2022-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_school_weight_alter_school_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='male',
            field=models.BooleanField(default=True),
        ),
    ]
