# Generated by Django 4.0.4 on 2022-06-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_school_news_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll', models.IntegerField()),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('adhar', models.BigIntegerField(default=132)),
                ('weight', models.FloatField(default=123, max_length=10)),
                ('male', models.BooleanField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('news_portal', models.URLField(default='')),
            ],
        ),
    ]
