# Generated by Django 4.0.4 on 2022-06-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='male',
            field=models.BooleanField(default=True),
        ),
    ]
