# Generated by Django 4.0.4 on 2022-06-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('color', models.BooleanField()),
                ('pwd1', models.CharField(max_length=20)),
                ('pwd2', models.CharField(max_length=20)),
            ],
        ),
    ]
